name:                mobo
version:             0.1.0.0
github:              "githubuser/mobo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mobo#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- utf8-string
- bytestring
- llvm-hs
- llvm-hs-pure
- llvm-hs-pretty

executables:
  mobo:
    main:                Main.hs
    source-dirs:         src/lang
    ghc-options:
    - -g
      # - -j
    # add C++ sources to the haskell library using the normal FFI stuff
    include-dirs: include
    c-sources:
    - src/kvm.cpp
    - src/main.cpp
    - src/machine.cpp
    - src/dev_mgr.cpp
    - src/vcpu.cpp
    - src/devices/serial.cpp
    - src/devices/posix.cpp
    cc-options: -std=c++17 -g

#extra-lib-dirs: build
##extra-libraries:
#  - mobo_rt
#  - stdc++
