[package]
name = "example"
version = "0.1.0"
edition = "2021"


[profile.dev]
# Must always use panic = "abort" to avoid needing to define the unstable eh_personality lang item.
panic = "abort"


[dependencies]
