;; generated by vectors.py - do not edit
;; handlers
default rel
extern alltraps
global vector0
vector0:
  push 0
  push 0
  jmp alltraps

global vector1
vector1:
  push 1
  push 1
  jmp alltraps

global vector2
vector2:
  push 2
  push 2
  jmp alltraps

global vector3
vector3:
  push 3
  push 3
  jmp alltraps

global vector4
vector4:
  push 4
  push 4
  jmp alltraps

global vector5
vector5:
  push 5
  push 5
  jmp alltraps

global vector6
vector6:
  push 6
  push 6
  jmp alltraps

global vector7
vector7:
  push 7
  push 7
  jmp alltraps

global vector8
vector8:
  push 8
  jmp alltraps

global vector9
vector9:
  push 9
  push 9
  jmp alltraps

global vector10
vector10:
  push 10
  jmp alltraps

global vector11
vector11:
  push 11
  jmp alltraps

global vector12
vector12:
  push 12
  jmp alltraps

global vector13
vector13:
  push 13
  jmp alltraps

global vector14
vector14:
  push 14
  jmp alltraps

global vector15
vector15:
  push 15
  push 15
  jmp alltraps

global vector16
vector16:
  push 16
  push 16
  jmp alltraps

global vector17
vector17:
  push 17
  jmp alltraps

global vector18
vector18:
  push 18
  push 18
  jmp alltraps

global vector19
vector19:
  push 19
  push 19
  jmp alltraps

global vector20
vector20:
  push 20
  push 20
  jmp alltraps

global vector21
vector21:
  push 21
  push 21
  jmp alltraps

global vector22
vector22:
  push 22
  push 22
  jmp alltraps

global vector23
vector23:
  push 23
  push 23
  jmp alltraps

global vector24
vector24:
  push 24
  push 24
  jmp alltraps

global vector25
vector25:
  push 25
  push 25
  jmp alltraps

global vector26
vector26:
  push 26
  push 26
  jmp alltraps

global vector27
vector27:
  push 27
  push 27
  jmp alltraps

global vector28
vector28:
  push 28
  push 28
  jmp alltraps

global vector29
vector29:
  push 29
  push 29
  jmp alltraps

global vector30
vector30:
  push 30
  push 30
  jmp alltraps

global vector31
vector31:
  push 31
  push 31
  jmp alltraps

global vector32
vector32:
  push 32
  push 32
  jmp alltraps

global vector33
vector33:
  push 33
  push 33
  jmp alltraps

global vector34
vector34:
  push 34
  push 34
  jmp alltraps

global vector35
vector35:
  push 35
  push 35
  jmp alltraps

global vector36
vector36:
  push 36
  push 36
  jmp alltraps

global vector37
vector37:
  push 37
  push 37
  jmp alltraps

global vector38
vector38:
  push 38
  push 38
  jmp alltraps

global vector39
vector39:
  push 39
  push 39
  jmp alltraps

global vector40
vector40:
  push 40
  push 40
  jmp alltraps

global vector41
vector41:
  push 41
  push 41
  jmp alltraps

global vector42
vector42:
  push 42
  push 42
  jmp alltraps

global vector43
vector43:
  push 43
  push 43
  jmp alltraps

global vector44
vector44:
  push 44
  push 44
  jmp alltraps

global vector45
vector45:
  push 45
  push 45
  jmp alltraps

global vector46
vector46:
  push 46
  push 46
  jmp alltraps

global vector47
vector47:
  push 47
  push 47
  jmp alltraps

global vector48
vector48:
  push 48
  push 48
  jmp alltraps

global vector49
vector49:
  push 49
  push 49
  jmp alltraps

global vector50
vector50:
  push 50
  push 50
  jmp alltraps

global vector51
vector51:
  push 51
  push 51
  jmp alltraps

global vector52
vector52:
  push 52
  push 52
  jmp alltraps

global vector53
vector53:
  push 53
  push 53
  jmp alltraps

global vector54
vector54:
  push 54
  push 54
  jmp alltraps

global vector55
vector55:
  push 55
  push 55
  jmp alltraps

global vector56
vector56:
  push 56
  push 56
  jmp alltraps

global vector57
vector57:
  push 57
  push 57
  jmp alltraps

global vector58
vector58:
  push 58
  push 58
  jmp alltraps

global vector59
vector59:
  push 59
  push 59
  jmp alltraps

global vector60
vector60:
  push 60
  push 60
  jmp alltraps

global vector61
vector61:
  push 61
  push 61
  jmp alltraps

global vector62
vector62:
  push 62
  push 62
  jmp alltraps

global vector63
vector63:
  push 63
  push 63
  jmp alltraps

global vector64
vector64:
  push 64
  push 64
  jmp alltraps

global vector65
vector65:
  push 65
  push 65
  jmp alltraps

global vector66
vector66:
  push 66
  push 66
  jmp alltraps

global vector67
vector67:
  push 67
  push 67
  jmp alltraps

global vector68
vector68:
  push 68
  push 68
  jmp alltraps

global vector69
vector69:
  push 69
  push 69
  jmp alltraps

global vector70
vector70:
  push 70
  push 70
  jmp alltraps

global vector71
vector71:
  push 71
  push 71
  jmp alltraps

global vector72
vector72:
  push 72
  push 72
  jmp alltraps

global vector73
vector73:
  push 73
  push 73
  jmp alltraps

global vector74
vector74:
  push 74
  push 74
  jmp alltraps

global vector75
vector75:
  push 75
  push 75
  jmp alltraps

global vector76
vector76:
  push 76
  push 76
  jmp alltraps

global vector77
vector77:
  push 77
  push 77
  jmp alltraps

global vector78
vector78:
  push 78
  push 78
  jmp alltraps

global vector79
vector79:
  push 79
  push 79
  jmp alltraps

global vector80
vector80:
  push 80
  push 80
  jmp alltraps

global vector81
vector81:
  push 81
  push 81
  jmp alltraps

global vector82
vector82:
  push 82
  push 82
  jmp alltraps

global vector83
vector83:
  push 83
  push 83
  jmp alltraps

global vector84
vector84:
  push 84
  push 84
  jmp alltraps

global vector85
vector85:
  push 85
  push 85
  jmp alltraps

global vector86
vector86:
  push 86
  push 86
  jmp alltraps

global vector87
vector87:
  push 87
  push 87
  jmp alltraps

global vector88
vector88:
  push 88
  push 88
  jmp alltraps

global vector89
vector89:
  push 89
  push 89
  jmp alltraps

global vector90
vector90:
  push 90
  push 90
  jmp alltraps

global vector91
vector91:
  push 91
  push 91
  jmp alltraps

global vector92
vector92:
  push 92
  push 92
  jmp alltraps

global vector93
vector93:
  push 93
  push 93
  jmp alltraps

global vector94
vector94:
  push 94
  push 94
  jmp alltraps

global vector95
vector95:
  push 95
  push 95
  jmp alltraps

global vector96
vector96:
  push 96
  push 96
  jmp alltraps

global vector97
vector97:
  push 97
  push 97
  jmp alltraps

global vector98
vector98:
  push 98
  push 98
  jmp alltraps

global vector99
vector99:
  push 99
  push 99
  jmp alltraps

global vector100
vector100:
  push 100
  push 100
  jmp alltraps

global vector101
vector101:
  push 101
  push 101
  jmp alltraps

global vector102
vector102:
  push 102
  push 102
  jmp alltraps

global vector103
vector103:
  push 103
  push 103
  jmp alltraps

global vector104
vector104:
  push 104
  push 104
  jmp alltraps

global vector105
vector105:
  push 105
  push 105
  jmp alltraps

global vector106
vector106:
  push 106
  push 106
  jmp alltraps

global vector107
vector107:
  push 107
  push 107
  jmp alltraps

global vector108
vector108:
  push 108
  push 108
  jmp alltraps

global vector109
vector109:
  push 109
  push 109
  jmp alltraps

global vector110
vector110:
  push 110
  push 110
  jmp alltraps

global vector111
vector111:
  push 111
  push 111
  jmp alltraps

global vector112
vector112:
  push 112
  push 112
  jmp alltraps

global vector113
vector113:
  push 113
  push 113
  jmp alltraps

global vector114
vector114:
  push 114
  push 114
  jmp alltraps

global vector115
vector115:
  push 115
  push 115
  jmp alltraps

global vector116
vector116:
  push 116
  push 116
  jmp alltraps

global vector117
vector117:
  push 117
  push 117
  jmp alltraps

global vector118
vector118:
  push 118
  push 118
  jmp alltraps

global vector119
vector119:
  push 119
  push 119
  jmp alltraps

global vector120
vector120:
  push 120
  push 120
  jmp alltraps

global vector121
vector121:
  push 121
  push 121
  jmp alltraps

global vector122
vector122:
  push 122
  push 122
  jmp alltraps

global vector123
vector123:
  push 123
  push 123
  jmp alltraps

global vector124
vector124:
  push 124
  push 124
  jmp alltraps

global vector125
vector125:
  push 125
  push 125
  jmp alltraps

global vector126
vector126:
  push 126
  push 126
  jmp alltraps

global vector127
vector127:
  push 127
  push 127
  jmp alltraps

global vector128
vector128:
  push 128
  push 128
  jmp alltraps

global vector129
vector129:
  push 129
  push 129
  jmp alltraps


; vector table
section .data
global vectors
vectors:
  dq vector0
  dq vector1
  dq vector2
  dq vector3
  dq vector4
  dq vector5
  dq vector6
  dq vector7
  dq vector8
  dq vector9
  dq vector10
  dq vector11
  dq vector12
  dq vector13
  dq vector14
  dq vector15
  dq vector16
  dq vector17
  dq vector18
  dq vector19
  dq vector20
  dq vector21
  dq vector22
  dq vector23
  dq vector24
  dq vector25
  dq vector26
  dq vector27
  dq vector28
  dq vector29
  dq vector30
  dq vector31
  dq vector32
  dq vector33
  dq vector34
  dq vector35
  dq vector36
  dq vector37
  dq vector38
  dq vector39
  dq vector40
  dq vector41
  dq vector42
  dq vector43
  dq vector44
  dq vector45
  dq vector46
  dq vector47
  dq vector48
  dq vector49
  dq vector50
  dq vector51
  dq vector52
  dq vector53
  dq vector54
  dq vector55
  dq vector56
  dq vector57
  dq vector58
  dq vector59
  dq vector60
  dq vector61
  dq vector62
  dq vector63
  dq vector64
  dq vector65
  dq vector66
  dq vector67
  dq vector68
  dq vector69
  dq vector70
  dq vector71
  dq vector72
  dq vector73
  dq vector74
  dq vector75
  dq vector76
  dq vector77
  dq vector78
  dq vector79
  dq vector80
  dq vector81
  dq vector82
  dq vector83
  dq vector84
  dq vector85
  dq vector86
  dq vector87
  dq vector88
  dq vector89
  dq vector90
  dq vector91
  dq vector92
  dq vector93
  dq vector94
  dq vector95
  dq vector96
  dq vector97
  dq vector98
  dq vector99
  dq vector100
  dq vector101
  dq vector102
  dq vector103
  dq vector104
  dq vector105
  dq vector106
  dq vector107
  dq vector108
  dq vector109
  dq vector110
  dq vector111
  dq vector112
  dq vector113
  dq vector114
  dq vector115
  dq vector116
  dq vector117
  dq vector118
  dq vector119
  dq vector120
  dq vector121
  dq vector122
  dq vector123
  dq vector124
  dq vector125
  dq vector126
  dq vector127
  dq vector128
  dq vector129
