;; generated by vectors.py - do not edit
;; handlers
extern alltraps
global vector0
vector0:
  push 0
  jmp alltraps
global vector1
vector1:
  push 1
  jmp alltraps
global vector2
vector2:
  push 2
  jmp alltraps
global vector3
vector3:
  push 3
  jmp alltraps
global vector4
vector4:
  push 4
  jmp alltraps
global vector5
vector5:
  push 5
  jmp alltraps
global vector6
vector6:
  push 6
  jmp alltraps
global vector7
vector7:
  push 7
  jmp alltraps
global vector8
vector8:
  push 8
  jmp alltraps
global vector9
vector9:
  push 9
  jmp alltraps
global vector10
vector10:
  push 10
  jmp alltraps
global vector11
vector11:
  push 11
  jmp alltraps
global vector12
vector12:
  push 12
  jmp alltraps
global vector13
vector13:
  push 13
  jmp alltraps
global vector14
vector14:
  push 14
  jmp alltraps
global vector15
vector15:
  push 15
  jmp alltraps
global vector16
vector16:
  push 16
  jmp alltraps
global vector17
vector17:
  push 17
  jmp alltraps
global vector18
vector18:
  push 18
  jmp alltraps
global vector19
vector19:
  push 19
  jmp alltraps
global vector20
vector20:
  push 20
  jmp alltraps
global vector21
vector21:
  push 21
  jmp alltraps
global vector22
vector22:
  push 22
  jmp alltraps
global vector23
vector23:
  push 23
  jmp alltraps
global vector24
vector24:
  push 24
  jmp alltraps
global vector25
vector25:
  push 25
  jmp alltraps
global vector26
vector26:
  push 26
  jmp alltraps
global vector27
vector27:
  push 27
  jmp alltraps
global vector28
vector28:
  push 28
  jmp alltraps
global vector29
vector29:
  push 29
  jmp alltraps
global vector30
vector30:
  push 30
  jmp alltraps
global vector31
vector31:
  push 31
  jmp alltraps
global vector32
vector32:
  push 32
  jmp alltraps
global vector33
vector33:
  push 33
  jmp alltraps
global vector34
vector34:
  push 34
  jmp alltraps
global vector35
vector35:
  push 35
  jmp alltraps
global vector36
vector36:
  push 36
  jmp alltraps
global vector37
vector37:
  push 37
  jmp alltraps
global vector38
vector38:
  push 38
  jmp alltraps
global vector39
vector39:
  push 39
  jmp alltraps
global vector40
vector40:
  push 40
  jmp alltraps
global vector41
vector41:
  push 41
  jmp alltraps
global vector42
vector42:
  push 42
  jmp alltraps
global vector43
vector43:
  push 43
  jmp alltraps
global vector44
vector44:
  push 44
  jmp alltraps
global vector45
vector45:
  push 45
  jmp alltraps
global vector46
vector46:
  push 46
  jmp alltraps
global vector47
vector47:
  push 47
  jmp alltraps
global vector48
vector48:
  push 48
  jmp alltraps
global vector49
vector49:
  push 49
  jmp alltraps
global vector50
vector50:
  push 50
  jmp alltraps
global vector51
vector51:
  push 51
  jmp alltraps
global vector52
vector52:
  push 52
  jmp alltraps
global vector53
vector53:
  push 53
  jmp alltraps
global vector54
vector54:
  push 54
  jmp alltraps
global vector55
vector55:
  push 55
  jmp alltraps
global vector56
vector56:
  push 56
  jmp alltraps
global vector57
vector57:
  push 57
  jmp alltraps
global vector58
vector58:
  push 58
  jmp alltraps
global vector59
vector59:
  push 59
  jmp alltraps
global vector60
vector60:
  push 60
  jmp alltraps
global vector61
vector61:
  push 61
  jmp alltraps
global vector62
vector62:
  push 62
  jmp alltraps
global vector63
vector63:
  push 63
  jmp alltraps
global vector64
vector64:
  push 64
  jmp alltraps
global vector65
vector65:
  push 65
  jmp alltraps
global vector66
vector66:
  push 66
  jmp alltraps
global vector67
vector67:
  push 67
  jmp alltraps
global vector68
vector68:
  push 68
  jmp alltraps
global vector69
vector69:
  push 69
  jmp alltraps
global vector70
vector70:
  push 70
  jmp alltraps
global vector71
vector71:
  push 71
  jmp alltraps
global vector72
vector72:
  push 72
  jmp alltraps
global vector73
vector73:
  push 73
  jmp alltraps
global vector74
vector74:
  push 74
  jmp alltraps
global vector75
vector75:
  push 75
  jmp alltraps
global vector76
vector76:
  push 76
  jmp alltraps
global vector77
vector77:
  push 77
  jmp alltraps
global vector78
vector78:
  push 78
  jmp alltraps
global vector79
vector79:
  push 79
  jmp alltraps
global vector80
vector80:
  push 80
  jmp alltraps
global vector81
vector81:
  push 81
  jmp alltraps
global vector82
vector82:
  push 82
  jmp alltraps
global vector83
vector83:
  push 83
  jmp alltraps
global vector84
vector84:
  push 84
  jmp alltraps
global vector85
vector85:
  push 85
  jmp alltraps
global vector86
vector86:
  push 86
  jmp alltraps
global vector87
vector87:
  push 87
  jmp alltraps
global vector88
vector88:
  push 88
  jmp alltraps
global vector89
vector89:
  push 89
  jmp alltraps
global vector90
vector90:
  push 90
  jmp alltraps
global vector91
vector91:
  push 91
  jmp alltraps
global vector92
vector92:
  push 92
  jmp alltraps
global vector93
vector93:
  push 93
  jmp alltraps
global vector94
vector94:
  push 94
  jmp alltraps
global vector95
vector95:
  push 95
  jmp alltraps
global vector96
vector96:
  push 96
  jmp alltraps
global vector97
vector97:
  push 97
  jmp alltraps
global vector98
vector98:
  push 98
  jmp alltraps
global vector99
vector99:
  push 99
  jmp alltraps
global vector100
vector100:
  push 100
  jmp alltraps
global vector101
vector101:
  push 101
  jmp alltraps
global vector102
vector102:
  push 102
  jmp alltraps
global vector103
vector103:
  push 103
  jmp alltraps
global vector104
vector104:
  push 104
  jmp alltraps
global vector105
vector105:
  push 105
  jmp alltraps
global vector106
vector106:
  push 106
  jmp alltraps
global vector107
vector107:
  push 107
  jmp alltraps
global vector108
vector108:
  push 108
  jmp alltraps
global vector109
vector109:
  push 109
  jmp alltraps
global vector110
vector110:
  push 110
  jmp alltraps
global vector111
vector111:
  push 111
  jmp alltraps
global vector112
vector112:
  push 112
  jmp alltraps
global vector113
vector113:
  push 113
  jmp alltraps
global vector114
vector114:
  push 114
  jmp alltraps
global vector115
vector115:
  push 115
  jmp alltraps
global vector116
vector116:
  push 116
  jmp alltraps
global vector117
vector117:
  push 117
  jmp alltraps
global vector118
vector118:
  push 118
  jmp alltraps
global vector119
vector119:
  push 119
  jmp alltraps
global vector120
vector120:
  push 120
  jmp alltraps
global vector121
vector121:
  push 121
  jmp alltraps
global vector122
vector122:
  push 122
  jmp alltraps
global vector123
vector123:
  push 123
  jmp alltraps
global vector124
vector124:
  push 124
  jmp alltraps
global vector125
vector125:
  push 125
  jmp alltraps
global vector126
vector126:
  push 126
  jmp alltraps
global vector127
vector127:
  push 127
  jmp alltraps
global vector128
vector128:
  push 128
  jmp alltraps
global vector129
vector129:
  push 129
  jmp alltraps
global vector130
vector130:
  push 130
  jmp alltraps
global vector131
vector131:
  push 131
  jmp alltraps
global vector132
vector132:
  push 132
  jmp alltraps
global vector133
vector133:
  push 133
  jmp alltraps
global vector134
vector134:
  push 134
  jmp alltraps
global vector135
vector135:
  push 135
  jmp alltraps
global vector136
vector136:
  push 136
  jmp alltraps
global vector137
vector137:
  push 137
  jmp alltraps
global vector138
vector138:
  push 138
  jmp alltraps
global vector139
vector139:
  push 139
  jmp alltraps
global vector140
vector140:
  push 140
  jmp alltraps
global vector141
vector141:
  push 141
  jmp alltraps
global vector142
vector142:
  push 142
  jmp alltraps
global vector143
vector143:
  push 143
  jmp alltraps
global vector144
vector144:
  push 144
  jmp alltraps
global vector145
vector145:
  push 145
  jmp alltraps
global vector146
vector146:
  push 146
  jmp alltraps
global vector147
vector147:
  push 147
  jmp alltraps
global vector148
vector148:
  push 148
  jmp alltraps
global vector149
vector149:
  push 149
  jmp alltraps
global vector150
vector150:
  push 150
  jmp alltraps
global vector151
vector151:
  push 151
  jmp alltraps
global vector152
vector152:
  push 152
  jmp alltraps
global vector153
vector153:
  push 153
  jmp alltraps
global vector154
vector154:
  push 154
  jmp alltraps
global vector155
vector155:
  push 155
  jmp alltraps
global vector156
vector156:
  push 156
  jmp alltraps
global vector157
vector157:
  push 157
  jmp alltraps
global vector158
vector158:
  push 158
  jmp alltraps
global vector159
vector159:
  push 159
  jmp alltraps
global vector160
vector160:
  push 160
  jmp alltraps
global vector161
vector161:
  push 161
  jmp alltraps
global vector162
vector162:
  push 162
  jmp alltraps
global vector163
vector163:
  push 163
  jmp alltraps
global vector164
vector164:
  push 164
  jmp alltraps
global vector165
vector165:
  push 165
  jmp alltraps
global vector166
vector166:
  push 166
  jmp alltraps
global vector167
vector167:
  push 167
  jmp alltraps
global vector168
vector168:
  push 168
  jmp alltraps
global vector169
vector169:
  push 169
  jmp alltraps
global vector170
vector170:
  push 170
  jmp alltraps
global vector171
vector171:
  push 171
  jmp alltraps
global vector172
vector172:
  push 172
  jmp alltraps
global vector173
vector173:
  push 173
  jmp alltraps
global vector174
vector174:
  push 174
  jmp alltraps
global vector175
vector175:
  push 175
  jmp alltraps
global vector176
vector176:
  push 176
  jmp alltraps
global vector177
vector177:
  push 177
  jmp alltraps
global vector178
vector178:
  push 178
  jmp alltraps
global vector179
vector179:
  push 179
  jmp alltraps
global vector180
vector180:
  push 180
  jmp alltraps
global vector181
vector181:
  push 181
  jmp alltraps
global vector182
vector182:
  push 182
  jmp alltraps
global vector183
vector183:
  push 183
  jmp alltraps
global vector184
vector184:
  push 184
  jmp alltraps
global vector185
vector185:
  push 185
  jmp alltraps
global vector186
vector186:
  push 186
  jmp alltraps
global vector187
vector187:
  push 187
  jmp alltraps
global vector188
vector188:
  push 188
  jmp alltraps
global vector189
vector189:
  push 189
  jmp alltraps
global vector190
vector190:
  push 190
  jmp alltraps
global vector191
vector191:
  push 191
  jmp alltraps
global vector192
vector192:
  push 192
  jmp alltraps
global vector193
vector193:
  push 193
  jmp alltraps
global vector194
vector194:
  push 194
  jmp alltraps
global vector195
vector195:
  push 195
  jmp alltraps
global vector196
vector196:
  push 196
  jmp alltraps
global vector197
vector197:
  push 197
  jmp alltraps
global vector198
vector198:
  push 198
  jmp alltraps
global vector199
vector199:
  push 199
  jmp alltraps
global vector200
vector200:
  push 200
  jmp alltraps
global vector201
vector201:
  push 201
  jmp alltraps
global vector202
vector202:
  push 202
  jmp alltraps
global vector203
vector203:
  push 203
  jmp alltraps
global vector204
vector204:
  push 204
  jmp alltraps
global vector205
vector205:
  push 205
  jmp alltraps
global vector206
vector206:
  push 206
  jmp alltraps
global vector207
vector207:
  push 207
  jmp alltraps
global vector208
vector208:
  push 208
  jmp alltraps
global vector209
vector209:
  push 209
  jmp alltraps
global vector210
vector210:
  push 210
  jmp alltraps
global vector211
vector211:
  push 211
  jmp alltraps
global vector212
vector212:
  push 212
  jmp alltraps
global vector213
vector213:
  push 213
  jmp alltraps
global vector214
vector214:
  push 214
  jmp alltraps
global vector215
vector215:
  push 215
  jmp alltraps
global vector216
vector216:
  push 216
  jmp alltraps
global vector217
vector217:
  push 217
  jmp alltraps
global vector218
vector218:
  push 218
  jmp alltraps
global vector219
vector219:
  push 219
  jmp alltraps
global vector220
vector220:
  push 220
  jmp alltraps
global vector221
vector221:
  push 221
  jmp alltraps
global vector222
vector222:
  push 222
  jmp alltraps
global vector223
vector223:
  push 223
  jmp alltraps
global vector224
vector224:
  push 224
  jmp alltraps
global vector225
vector225:
  push 225
  jmp alltraps
global vector226
vector226:
  push 226
  jmp alltraps
global vector227
vector227:
  push 227
  jmp alltraps
global vector228
vector228:
  push 228
  jmp alltraps
global vector229
vector229:
  push 229
  jmp alltraps
global vector230
vector230:
  push 230
  jmp alltraps
global vector231
vector231:
  push 231
  jmp alltraps
global vector232
vector232:
  push 232
  jmp alltraps
global vector233
vector233:
  push 233
  jmp alltraps
global vector234
vector234:
  push 234
  jmp alltraps
global vector235
vector235:
  push 235
  jmp alltraps
global vector236
vector236:
  push 236
  jmp alltraps
global vector237
vector237:
  push 237
  jmp alltraps
global vector238
vector238:
  push 238
  jmp alltraps
global vector239
vector239:
  push 239
  jmp alltraps
global vector240
vector240:
  push 240
  jmp alltraps
global vector241
vector241:
  push 241
  jmp alltraps
global vector242
vector242:
  push 242
  jmp alltraps
global vector243
vector243:
  push 243
  jmp alltraps
global vector244
vector244:
  push 244
  jmp alltraps
global vector245
vector245:
  push 245
  jmp alltraps
global vector246
vector246:
  push 246
  jmp alltraps
global vector247
vector247:
  push 247
  jmp alltraps
global vector248
vector248:
  push 248
  jmp alltraps
global vector249
vector249:
  push 249
  jmp alltraps
global vector250
vector250:
  push 250
  jmp alltraps
global vector251
vector251:
  push 251
  jmp alltraps
global vector252
vector252:
  push 252
  jmp alltraps
global vector253
vector253:
  push 253
  jmp alltraps
global vector254
vector254:
  push 254
  jmp alltraps
global vector255
vector255:
  push 255
  jmp alltraps

; vector table
section .data
global vectors
vectors:
  dq vector0
  dq vector1
  dq vector2
  dq vector3
  dq vector4
  dq vector5
  dq vector6
  dq vector7
  dq vector8
  dq vector9
  dq vector10
  dq vector11
  dq vector12
  dq vector13
  dq vector14
  dq vector15
  dq vector16
  dq vector17
  dq vector18
  dq vector19
  dq vector20
  dq vector21
  dq vector22
  dq vector23
  dq vector24
  dq vector25
  dq vector26
  dq vector27
  dq vector28
  dq vector29
  dq vector30
  dq vector31
  dq vector32
  dq vector33
  dq vector34
  dq vector35
  dq vector36
  dq vector37
  dq vector38
  dq vector39
  dq vector40
  dq vector41
  dq vector42
  dq vector43
  dq vector44
  dq vector45
  dq vector46
  dq vector47
  dq vector48
  dq vector49
  dq vector50
  dq vector51
  dq vector52
  dq vector53
  dq vector54
  dq vector55
  dq vector56
  dq vector57
  dq vector58
  dq vector59
  dq vector60
  dq vector61
  dq vector62
  dq vector63
  dq vector64
  dq vector65
  dq vector66
  dq vector67
  dq vector68
  dq vector69
  dq vector70
  dq vector71
  dq vector72
  dq vector73
  dq vector74
  dq vector75
  dq vector76
  dq vector77
  dq vector78
  dq vector79
  dq vector80
  dq vector81
  dq vector82
  dq vector83
  dq vector84
  dq vector85
  dq vector86
  dq vector87
  dq vector88
  dq vector89
  dq vector90
  dq vector91
  dq vector92
  dq vector93
  dq vector94
  dq vector95
  dq vector96
  dq vector97
  dq vector98
  dq vector99
  dq vector100
  dq vector101
  dq vector102
  dq vector103
  dq vector104
  dq vector105
  dq vector106
  dq vector107
  dq vector108
  dq vector109
  dq vector110
  dq vector111
  dq vector112
  dq vector113
  dq vector114
  dq vector115
  dq vector116
  dq vector117
  dq vector118
  dq vector119
  dq vector120
  dq vector121
  dq vector122
  dq vector123
  dq vector124
  dq vector125
  dq vector126
  dq vector127
  dq vector128
  dq vector129
  dq vector130
  dq vector131
  dq vector132
  dq vector133
  dq vector134
  dq vector135
  dq vector136
  dq vector137
  dq vector138
  dq vector139
  dq vector140
  dq vector141
  dq vector142
  dq vector143
  dq vector144
  dq vector145
  dq vector146
  dq vector147
  dq vector148
  dq vector149
  dq vector150
  dq vector151
  dq vector152
  dq vector153
  dq vector154
  dq vector155
  dq vector156
  dq vector157
  dq vector158
  dq vector159
  dq vector160
  dq vector161
  dq vector162
  dq vector163
  dq vector164
  dq vector165
  dq vector166
  dq vector167
  dq vector168
  dq vector169
  dq vector170
  dq vector171
  dq vector172
  dq vector173
  dq vector174
  dq vector175
  dq vector176
  dq vector177
  dq vector178
  dq vector179
  dq vector180
  dq vector181
  dq vector182
  dq vector183
  dq vector184
  dq vector185
  dq vector186
  dq vector187
  dq vector188
  dq vector189
  dq vector190
  dq vector191
  dq vector192
  dq vector193
  dq vector194
  dq vector195
  dq vector196
  dq vector197
  dq vector198
  dq vector199
  dq vector200
  dq vector201
  dq vector202
  dq vector203
  dq vector204
  dq vector205
  dq vector206
  dq vector207
  dq vector208
  dq vector209
  dq vector210
  dq vector211
  dq vector212
  dq vector213
  dq vector214
  dq vector215
  dq vector216
  dq vector217
  dq vector218
  dq vector219
  dq vector220
  dq vector221
  dq vector222
  dq vector223
  dq vector224
  dq vector225
  dq vector226
  dq vector227
  dq vector228
  dq vector229
  dq vector230
  dq vector231
  dq vector232
  dq vector233
  dq vector234
  dq vector235
  dq vector236
  dq vector237
  dq vector238
  dq vector239
  dq vector240
  dq vector241
  dq vector242
  dq vector243
  dq vector244
  dq vector245
  dq vector246
  dq vector247
  dq vector248
  dq vector249
  dq vector250
  dq vector251
  dq vector252
  dq vector253
  dq vector254
  dq vector255
