out = lib/libc.a


srcs += chariot/yield.c
srcs += chariot/proc.c
srcs += stdio/stdio.c
srcs += stdio/putchar.c
srcs += stdio/printf.c
srcs += stdlib/liballoc.c
srcs += stdlib/malloc.c
srcs += syscall.asm
srcs += mman/mmap.c
srcs += string/mem.c
srcs += string/string.c
srcs += stack_chk_fail.c
srcs += lib.c
srcs += fcntl.c
srcs += unistd.c
srcs += syscall.c
srcs += start.asm
srcs += stat.c
srcs += pthread.c
