src-$(CONFIG_ATA) += $(shell find drivers/ata -name "*.cpp" -or -name "*.asm" -or -name "*.c")
src-$(CONFIG_CHAR) += $(shell find drivers/char -name "*.cpp" -or -name "*.asm" -or -name "*.c")
src-$(CONFIG_PS2MOUSE) += $(shell find drivers/mouse -name "*.cpp" -or -name "*.asm" -or -name "*.c")
src-$(CONFIG_PS2KBD) += $(shell find drivers/kbd -name "*.cpp" -or -name "*.asm" -or -name "*.c")

# networking
src-$(CONFIG_E1000) += $(shell find drivers/e1000 -name "*.cpp" -or -name "*.asm" -or -name "*.c")
src-$(CONFIG_RTL8139) += $(shell find drivers/RTL8139 -name "*.cpp" -or -name "*.asm" -or -name "*.c")

# audio
src-$(CONFIG_SB16) += $(shell find drivers/sb16 -name "*.cpp" -or -name "*.asm" -or -name "*.c")

# video
src-$(CONFIG_VGA) += $(shell find drivers/vga -name "*.cpp" -or -name "*.asm" -or -name "*.c")
